# Generated by Django 3.2.4 on 2025-01-27 07:02

from django.db import migrations
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='crop_it_photo',
            field=imageit.models.CropItImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='scale_photo',
            field=imageit.models.ScaleItImageField(blank=True, null=True, upload_to=''),
        ),
    ]
