# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Auto Bump Version Minor
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  auto-bump-version-minor:
    name: Modifiy value in version.txt file
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Update PIP 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Modifiy basic version number minor
        run: |
          vers=$(<version.txt)
          majorvers=$(echo "$vers" | grep -o '.*\.')
          minorvers=$(echo "$vers" | grep -o '[0-9]*$')
          newminor=$((minorvers + 1))
          echo "$majorvers$newminor" > version.txt
      - name: Commit report
        run: |
          git config --global user.name 'Scott James'
          git config --global user.email 'scotty.james95@icloud.com'
          git commit -am "Auto Minor Version Bump"
          git push